### ISSUE TITLE
pandoc 1.14 compatibility

### ISSUE THREAD

**Issue by agitter** [sergiocorreia/panflute#192]
I noticed panflute 2.1 supports pandoc versions 2.11.0.4—2.13.x.  Are there any known incompatibilities with the very recently released pandoc 2.14.x?

**Comment by dhimmel** [comment]
The issue for us is that the panflute-feedback for conda-forge is [adding](https://github.com/conda-forge/panflute-feedstock/blob/f98d8eb7c6fec2334d220c684f1e64c082b81adc/recipe/meta.yaml#L5-L6) the pandoc version to the requirements:

```yaml
# exclusive
{% set pandoc_maximum_version = "2.14" %}
...
requirements:
  run_constrained:
    - pandoc >={{ pandoc_minimum_version }},<{{ pandoc_maximum_version }}
```

My understanding is that the Pandoc types API version is all that actually matters for filter compatibility, not the pandoc version. So if Pandoc 2.14 still uses pandoc-types 1.22, there won't actually be any issues.

So would it be fair to say that the issue here is that the panflute readme preemptively stated that 2.14 wasn't compatible, even though it ended up being compatible. And then the panflute-feedback developers codified that in the conda recipe?
