### ISSUE TITLE
Trying to create new metadata from metadata

### ISSUE THREAD

**Issue by lakonis** [sergiocorreia/panflute#232]
I am trying to create a new key `author` from existing key `authors`.

`authors`:
```yaml
authors:
  - biography: >-
      my wonderfull biography
      following biography
    forname: Arnaud
    surname: Wormser
  - biography: >-
      my wonderfull biography
      following biography
    forname: Gérard
    surname: Genon
```

`author`:
```yaml
author:
  - biography: >-
      my wonderfull biography
      following biography
    name: Arnaud Genon
  - biography: >-
      my wonderfull biography
      following biography
    name: Gérard Wormser
```

I understand the `get_metadata` function, but I don't see how to *put* new `key:value` into the metadata block.

I am new to panflute and to pandoc filters in general. I can write Python though, but I'm not familiar with the AST or JSON structure that is manipulated by pandoc filters.
