### ISSUE TITLE
MyPy Support

### ISSUE THREAD

**Issue by acederberg** [sergiocorreia/panflute#253]
Hi!

I am checking my code with ``mypy`` and would like to ask that we somehow add support. When I run mypy on my filters I get the following message:

```stderr
scripts/filters/util.py:7: error: Skipping analyzing "panflute": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

This will not take much (so I suppose) and [the work involved](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports) is pretty minimal.
Let me know if there are any issues with this and eventually I might get around to making a PR about it.

**Comment by acederberg** [comment]
For now, I am doing 

```toml
[tool.mypy]
overrides = [
  {module = "panflute.*",ignore_missing_imports=true},
]
```

in ``pyproject.toml`` to suppress these errors.
